### ISSUE TITLE
No option to enable P4G.exe

### ISSUE THREAD

**Issue by Araraura** [zarroboogs/p4gpc.tinyfixes#2]
I'm trying to install the mod, but I cannot find P4G.exe in Reloaded II. I was able to download the Steam Hooks, but when I go to managed mods and select it, there's no option to enable anything anywhere.

**Comment by Araraura** [comment]
btw I know this isn't the right repository, but since the P4G cheat engine doesn't have an issues page then this is the only place where I can ask if you plan to update that to 1.1 which came out today.

**Comment by zarroboogs** [comment]
Did you add `P4G.exe` to Reloaded II?

Just in case:

1. Click *Add an Application*.
2. Click *New*.
3. Navigate to `<game_path>/P4G.exe`.
4. Click *Open*.

<details>
<summary>Preview (click to expand)</summary>

![add](https://user-images.githubusercontent.com/36057965/92058345-f9804880-ed97-11ea-8dc2-854312713f57.png)

</details>

Then in *Manage Mods*, click on *Persona 4 Golden Tiny Fixes* and enable it for `P4G.exe` via the checkbox.

<details>
<summary>Preview (click to expand)</summary>

![manage](https://user-images.githubusercontent.com/36057965/92060370-39e1c580-ed9c-11ea-9080-63e0b8c75240.png)

</details>

---

Regarding the cheat table, it works with all versions of the game so far (v1.0, all hotfixes and v1.1).

**Comment by Araraura** [comment]
got it, thanks for the info
